-- Exercicio

CREATE DATABASE exercicio;

USE exercicio;
	CREATE TABLE A(
		Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        A1 VARCHAR(10),
		A2 VARCHAR(20),
        A3 VARCHAR(30),
        A4 VARCHAR(40),
        A5 VARCHAR(50)
	);
    CREATE TABLE B(
		Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        B1 VARCHAR(10),
		B2 VARCHAR(20),
        B3 VARCHAR(30),
        B4 VARCHAR(40),
        B5 VARCHAR(50)
	);
    CREATE TABLE c(
		Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        C1 VARCHAR(10),
		C2 VARCHAR(20),
        C3 VARCHAR(30),
        C4 VARCHAR(40),
        C5 VARCHAR(50)
	);